name: ReferenceApp
options:
  bundleIdPrefix: com.spruceid.mobile
packages:
  SpruceIDMobileSdk:
    url: https://github.com/spruceid/mobile-sdk-swift
    from: 0.0.9
    # path: "../mobile-sdk-swift"
settings:
  ENABLE_USER_SCRIPT_SANDBOXING: YES
  ENABLE_MODULE_VERIFIER: YES
  DEVELOPMENT_TEAM: FZVYR3KYL4
  # "CODE_SIGN_IDENTITY": "Spruce Systems, Inc. (FZVYR3KYL4)"
targets:
  App:
    type: application
    supportedDestinations: [iOS]
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: "Targets/App/Sources"
        createIntermediateGroups: true
    resources:
      - path: "Resources"
        createIntermediateGroups: true
    dependencies:
      - target: AppAppKit
      - target: AppUIKit
    info:
      path: Info.plist
      properties:
        CFBundleVersion: "0.0.2"
        CFBundleShortVersionString: "0.0.2"
        CFBundleDisplayName: "SpruceKit Reference App"
        CFBundleIconName: "AppIcon"
        CFBundlePackageType: "APPL"
        NSBluetoothAlwaysUsageDescription: "Secure transmission of mobile DL data"
        NSCameraUsageDescription: "Secure transmission of mobile DL data"
        ITSAppUsesNonExemptEncryption: "NO"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.spruceid.mobile
  AppAppKit:
    type: framework
    supportedDestinations: [iOS]
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: "Targets/AppAppKit/Sources"
        createIntermediateGroups: true
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.spruceid.mobile.kit
  AppAppKitTests:
    type: bundle.unit-test
    supportedDestinations: [iOS]
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: "Targets/AppAppKit/Tests"
        createIntermediateGroups: true
    dependencies:
      - target: AppAppKit
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.spruceid.mobile.kittests
  AppUIKit:
    type: framework
    supportedDestinations: [iOS]
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: "Targets/AppUIKit/Sources"
        createIntermediateGroups: true
    dependencies:
      - package: SpruceIDMobileSdk
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.spruceid.mobile.ui
  AppUIKitTests:
    type: bundle.unit-test
    supportedDestinations: [iOS]
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: "Targets/AppUIKit/Tests"
        createIntermediateGroups: true
    dependencies:
      - target: AppUIKit
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.spruceid.mobile.uitests
configs:
  debug: debug
  release: release
schemes:
  release:
    shared: true
    build:
      targets:
        App: [build, archive]
    run:
      targets:
        App: [run]
    archive:
      config: release
  debug:
    shared: true
    build:
      targets:
        App: [build, archive]
    run:
      targets:
        App: [run]
    archive:
      config: debug
